/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dispersion;

/**
 *
 * @author Usuario
 */
public class GUI extends javax.swing.JFrame {

    private int numDispersion;

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        lDigiteLlave = new javax.swing.JLabel();
        txtClave = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumDispersion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        PNLDivision = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtTamanioArregloDiv = new javax.swing.JTextField();
        btnMetodoDivision = new javax.swing.JButton();
        btnSimularMetodoDivision = new javax.swing.JButton();
        PNLDivision1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTamanioArregloDiv1 = new javax.swing.JTextField();
        btnMetodoDivision1 = new javax.swing.JButton();
        PNLDivision2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTamanioArregloDiv2 = new javax.swing.JTextField();
        btnMetodoDivision2 = new javax.swing.JButton();
        PNLDivision3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtTamanioArregloDiv3 = new javax.swing.JTextField();
        btnMetodoDivision3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lTitulo.setText("Métodos para calcular el número de Dispersión. ");

        lDigiteLlave.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        lDigiteLlave.setText("Digite llave:");

        txtClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtClaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("Número de dispersión:");

        txtNumDispersion.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        txtNumDispersion.setVerifyInputWhenFocusTarget(false);
        txtNumDispersion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumDispersionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Método de división");

        PNLDivision.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Digite tamaño del arreglo:");

        txtTamanioArregloDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioArregloDivActionPerformed(evt);
            }
        });

        btnMetodoDivision.setText("Método de división");
        btnMetodoDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoDivisionActionPerformed(evt);
            }
        });

        btnSimularMetodoDivision.setText("Simulador");
        btnSimularMetodoDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimularMetodoDivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDivisionLayout = new javax.swing.GroupLayout(PNLDivision);
        PNLDivision.setLayout(PNLDivisionLayout);
        PNLDivisionLayout.setHorizontalGroup(
            PNLDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PNLDivisionLayout.createSequentialGroup()
                        .addGroup(PNLDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTamanioArregloDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(PNLDivisionLayout.createSequentialGroup()
                        .addComponent(btnMetodoDivision)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimularMetodoDivision)
                        .addGap(14, 14, 14))))
        );
        PNLDivisionLayout.setVerticalGroup(
            PNLDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivisionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanioArregloDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PNLDivisionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMetodoDivision)
                    .addComponent(btnSimularMetodoDivision))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        PNLDivision1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setText("Digite tamaño del arreglo:");

        txtTamanioArregloDiv1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioArregloDiv1ActionPerformed(evt);
            }
        });

        btnMetodoDivision1.setText("Método de división");
        btnMetodoDivision1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoDivision1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDivision1Layout = new javax.swing.GroupLayout(PNLDivision1);
        PNLDivision1.setLayout(PNLDivision1Layout);
        PNLDivision1Layout.setHorizontalGroup(
            PNLDivision1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLDivision1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanioArregloDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoDivision1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLDivision1Layout.setVerticalGroup(
            PNLDivision1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanioArregloDiv1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMetodoDivision1)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        PNLDivision2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setText("Digite tamaño del arreglo:");

        txtTamanioArregloDiv2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioArregloDiv2ActionPerformed(evt);
            }
        });

        btnMetodoDivision2.setText("Método de división");
        btnMetodoDivision2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoDivision2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDivision2Layout = new javax.swing.GroupLayout(PNLDivision2);
        PNLDivision2.setLayout(PNLDivision2Layout);
        PNLDivision2Layout.setHorizontalGroup(
            PNLDivision2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLDivision2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanioArregloDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoDivision2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PNLDivision2Layout.setVerticalGroup(
            PNLDivision2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanioArregloDiv2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMetodoDivision2)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        PNLDivision3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Digite tamaño del arreglo:");

        txtTamanioArregloDiv3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioArregloDiv3ActionPerformed(evt);
            }
        });

        btnMetodoDivision3.setText("Método de división");
        btnMetodoDivision3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoDivision3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PNLDivision3Layout = new javax.swing.GroupLayout(PNLDivision3);
        PNLDivision3.setLayout(PNLDivision3Layout);
        PNLDivision3Layout.setHorizontalGroup(
            PNLDivision3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PNLDivision3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTamanioArregloDiv3, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMetodoDivision3))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        PNLDivision3Layout.setVerticalGroup(
            PNLDivision3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PNLDivision3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTamanioArregloDiv3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMetodoDivision3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Método de división");

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Método de división");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Método de división");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lDigiteLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(PNLDivision2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNLDivision, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNLDivision3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNLDivision1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 657, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumDispersion, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lDigiteLlave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClave))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumDispersion, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PNLDivision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PNLDivision1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PNLDivision2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PNLDivision3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtClaveActionPerformed

    private void txtNumDispersionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumDispersionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumDispersionActionPerformed

    private void txtTamanioArregloDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioArregloDivActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanioArregloDivActionPerformed

    private void btnMetodoDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoDivisionActionPerformed
        try {
            int tamArreglo = Integer.parseInt(txtTamanioArregloDiv.getText());
            boolean esPrimo = true;
            if (tamArreglo < 0) {
                txtNumDispersion.setText("Favor escriba un número mayor que 0");
            } else if (tamArreglo % 2 == 0 && tamArreglo != 2) {
                txtNumDispersion.setText("Favor digite un número primo para el tamaño del arreglo.");
            } else {
                for (int i = 3; i * i <= tamArreglo; i += 2) {
                    if (tamArreglo % i == 0) {
                        esPrimo = false;
                    }
                }

                if (esPrimo) {
                    int clave = Integer.parseInt(txtClave.getText());
                    numDispersion = clave % tamArreglo;
                    txtNumDispersion.setText(String.valueOf(numDispersion));
                    
                }
            }

        } catch (NumberFormatException e) {
            txtNumDispersion.setText("Favor escriba un número mayor que 0");
            System.out.println("Error: el valor del campo 'Número de dispersión' contiene caracteres no numéricos");
        }
    }//GEN-LAST:event_btnMetodoDivisionActionPerformed

    private void txtTamanioArregloDiv1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioArregloDiv1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanioArregloDiv1ActionPerformed

    private void btnMetodoDivision1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoDivision1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodoDivision1ActionPerformed

    private void txtTamanioArregloDiv2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioArregloDiv2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanioArregloDiv2ActionPerformed

    private void btnMetodoDivision2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoDivision2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodoDivision2ActionPerformed

    private void txtTamanioArregloDiv3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioArregloDiv3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanioArregloDiv3ActionPerformed

    private void btnMetodoDivision3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoDivision3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMetodoDivision3ActionPerformed

    private void btnSimularMetodoDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimularMetodoDivisionActionPerformed
        MDivision mDivision = new MDivision();
        
    }//GEN-LAST:event_btnSimularMetodoDivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PNLDivision;
    private javax.swing.JPanel PNLDivision1;
    private javax.swing.JPanel PNLDivision2;
    private javax.swing.JPanel PNLDivision3;
    private javax.swing.JButton btnMetodoDivision;
    private javax.swing.JButton btnMetodoDivision1;
    private javax.swing.JButton btnMetodoDivision2;
    private javax.swing.JButton btnMetodoDivision3;
    private javax.swing.JButton btnSimularMetodoDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lDigiteLlave;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField txtClave;
    private javax.swing.JTextField txtNumDispersion;
    private javax.swing.JTextField txtTamanioArregloDiv;
    private javax.swing.JTextField txtTamanioArregloDiv1;
    private javax.swing.JTextField txtTamanioArregloDiv2;
    private javax.swing.JTextField txtTamanioArregloDiv3;
    // End of variables declaration//GEN-END:variables
}
